name: Center Core
favicon: null
layout_spectrum: 0.4987
typography_spectrum: 0.6797960181720555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffcf06'
    - '#15487d'
    - '#bdbec0'
    - '#6d8cad'
  brandStrength: 0.9377424130216241
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
