name: Center Core
favicon: null
layout_spectrum: 0.20185900339856744
typography_spectrum: 0.6797960181720555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9377424130216241
  lightness: 0.30939369136467576
  saturation: 0.6939048117492348
  rhythmicContrast: 0.6009613831993192
purpose: []
